## Importation des librairies

In [58]:
import pandapower as pp
import pandas as pd
import numpy as np

## Récuperation du fichier pickle

In [59]:
net_pickle = pp.from_pickle('input-data/trey_net_student.p')

net_pickle.bus # Affiche les informations des bus, un slack et 11 PQ (charges)

            name   type   zone  in_service
0     STMT003438     PQ  Trafo        True
1     CDBT004764     PQ  North        True
2     CDBT003746     PQ  North        True
3     CDBT004760     PQ  North        True
4     CDBT012139     PQ  North        True
5     CDBT900784     PQ  North        True
6     CDBT901452     PQ  South        True
7     CDBT004774     PQ  South        True
8     CDBT901604     PQ  South        True
9     CDBT016055     PQ  South        True
10            N1     PQ  South        True
11         60437     PQ  South        True
12  STMT003438HV  Slack  Trafo        True

In [60]:
net_pickle.line

              name  from_bus  to_bus  g_us_per_km   df std_type  in_service
0     GKN3x150_150         0       1          0.0  1.0     None        True
1   GKN3x150_150_2         1       2          0.0  1.0     None        True
2       GKN3X95_95         1       3          0.0  1.0     None        True
3       GKT3X50_50         3       4          0.0  1.0     None        True
4     GKT3X50_50_2         4       5          0.0  1.0     None        True
5   GKN3x150_150_3         0       6          0.0  1.0     None        True
6     GKN3X95_95_2         6       7          0.0  1.0     None        True
7   GKN3x150_150_4         7       8          0.0  1.0     None        True
8       GKN3X50_50         7       9          0.0  1.0     None        True
9     GKN3X50_50_2         6      10          0.0  1.0     None        True
10    GKN3X240_240         0      11          0.0  1.0     None        True

In [61]:
# Configure les paramètres des lignes du réseau
net_pickle.line.insert(0,"length_km", [0.18, 0.1, 0.115, 0.08, 0.09, 0.135, 0.1, 0.205, 0.085, 0.255, 0.340])
net_pickle.line.insert(0, "r_ohm_per_km", [0.124, 0.124, 0.193, 0.387, 0.387, 0.124, 0.193, 0.124, 0.387, 0.387, 0.0754])
net_pickle.line.insert(0, "x_ohm_per_km", [0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07])
net_pickle.line.insert(0, "c_nf_per_km", [349, 349, 338, 298, 298, 349, 338, 349, 298, 298, 346])
net_pickle.line.insert(0, "max_i_ka", [0.4, 0.4, 0.252, 0.170, 0.170, 0.4, 0.252, 0.4, 0.170, 0.170, 0.512])
net_pickle.line.insert(0, "parallel", [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [62]:
net_pickle.line

,parallel,max_i_ka,c_nf_per_km,x_ohm_per_km,r_ohm_per_km,length_km,name,from_bus,to_bus,g_us_per_km,df,std_type,in_service
0,1,0.400,349,0.07,0.1240,0.180,GKN3x150_150,0,1,0.0,1.0,None,True
1,1,0.400,349,0.07,0.1240,0.100,GKN3x150_150_2,1,2,0.0,1.0,None,True
2,1,0.252,338,0.07,0.1930,0.115,GKN3X95_95,1,3,0.0,1.0,None,True
3,1,0.170,298,0.07,0.3870,0.080,GKT3X50_50,3,4,0.0,1.0,None,True
4,1,0.170,298,0.07,0.3870,0.090,GKT3X50_50_2,4,5,0.0,1.0,None,True
5,1,0.400,349,0.07,0.1240,0.135,GKN3x150_150_3,0,6,0.0,1.0,None,True
6,1,0.252,338,0.07,0.1930,0.100,GKN3X95_95_2,6,7,0.0,1.0,None,True
7,1,0.400,349,0.07,0.1240,0.205,GKN3x150_150_4,7,8,0.0,1.0,None,True
8,1,0.170,298,0.07,0.3870,0.085,GKN3X50_50,7,9,0.0,1.0,None,True
9,1,0.170,298,0.07,0.3870,0.255,GKN3X50_50_2,6,10,0.0,1.0,None,True
10,1,0.512,346,0.07,0.0754,0.340,GKN3X240_240,0,11,0.0,1.0,None,True

In [63]:
net_pickle.trafo

,name,hv_bus,lv_bus,sn_mva,vn_hv_kv,vn_lv_kv,vk_percent,vkr_percent,pfe_kw,i0_percent,vector_group,vk0_percent,vkr0_percent,mag0_percent,mag0_rx,si0_hv_partial,shift_degree,tap_side,tap_neutral,tap_min,tap_max,tap_step_percent,tap_step_degree,tap_pos,tap_phase_shifter,parallel,std_type,df,in_service
0,STMT003438,12,0,0.63,18.3,0.42,4.0,0.42,0.65,1.8,Dyn,3.0,0.75,0.3,1.9,1.9,0.0,lv,0,-3,3,2.0,0.0,-3,False,1,None,1.0,True

In [64]:
net_pickle.load # Affiche les informations des charges

          name  bus  const_z_percent  const_i_percent sn_mva  in_service type
0   STMT003438    0              0.0              0.0   None        True  wye
1   CDBT004764    1              0.0              0.0   None        True  wye
2   CDBT003746    2              0.0              0.0   None        True  wye
3   CDBT004760    3              0.0              0.0   None        True  wye
4   CDBT012139    4              0.0              0.0   None        True  wye
5   CDBT900784    5              0.0              0.0   None        True  wye
6   CDBT901452    6              0.0              0.0   None        True  wye
7   CDBT004774    7              0.0              0.0   None        True  wye
8   CDBT901604    8              0.0              0.0   None        True  wye
9   CDBT016055    9              0.0              0.0   None        True  wye
10          N1   10              0.0              0.0   None        True  wye
11       60437   11              0.0              0.0   None        True  wye